name: Build Ramble Linux Package

on:
  push:
    branches: [ main, correction ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Linux Package
      uses: docker/build-push-action@v5
      with:
        context: .
        file: - # Use Dockerfile.linux created inline
        push: false
        outputs: type=local,dest=./dist
        build-args: |
          GO_VERSION=1.23
        build-contexts: |
          whisper-builder=docker-image://debian:bookworm-slim
        # Create the Dockerfile inline for the build
        inline: |
          # First stage: build whisper.cpp library
          FROM whisper-builder as whisper-builder

          # Install build dependencies
          RUN apt-get update && apt-get install -y \
              build-essential \
              cmake \
              git \
              g++

          # Clone and build whisper.cpp
          WORKDIR /app/whisper.cpp
          RUN git clone --depth 1 https://github.com/ggerganov/whisper.cpp.git .
          RUN mkdir -p build && cd build && \
              cmake -DBUILD_SHARED_LIBS=ON .. && \
              cmake --build . --config Release --parallel $(nproc)

          # Second stage: build the Go application
          FROM golang:1.21 as builder

          # Install dependencies needed for GUI
          RUN apt-get update && apt-get install -y \
              gcc libasound2-dev libgl1-mesa-dev libxcursor-dev \
              libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev \
              xorg-dev libgl1-mesa-dev libx11-dev libxcursor-dev libxi-dev \
              libxinerama-dev libxrandr-dev libxxf86vm-dev

          WORKDIR /app

          # Copy the repository contents
          COPY . .

          # Create necessary directories
          RUN mkdir -p /app/pkg/transcription/embed/binaries/linux-amd64
          RUN mkdir -p /app/pkg/transcription/embed/models
          # Make sure include directory exists
          RUN mkdir -p /app/third_party/whisper.cpp/include

          # Copy whisper.cpp headers and libraries from the first stage
          COPY --from=whisper-builder /app/whisper.cpp/include/whisper.h /app/third_party/whisper.cpp/include/
          COPY --from=whisper-builder /app/whisper.cpp/build/libwhisper.so /app/pkg/transcription/embed/binaries/linux-amd64/

          # Create directories for the final package
          RUN mkdir -p /app/dist/linux-pkg/libs && \
              mkdir -p /app/dist/linux-pkg/models

          # Set CGO environment variables to find the whisper header
          ENV CGO_ENABLED=1
          ENV CGO_CFLAGS="-I/app/third_party/whisper.cpp/include"
          ENV CGO_LDFLAGS="-L/app/pkg/transcription/embed/binaries/linux-amd64 -lwhisper"

          # Build with Go whisper bindings tag and rpath
          RUN echo "Building Linux binary..." && \
              go build -v -tags=whisper_go \
              -ldflags="-s -w -extldflags '-Wl,-rpath,\$ORIGIN/libs'" \
              -o /app/dist/linux-pkg/ramble ./cmd/ramble

          # Copy libraries and prepare package
          RUN cp /app/pkg/transcription/embed/binaries/linux-amd64/libwhisper.so /app/dist/linux-pkg/libs/ && \
              cp -r /app/assets /app/dist/linux-pkg/ && \
              chmod +x /app/dist/linux-pkg/ramble && \
              cd /app/dist && \
              tar -czf ramble-linux-amd64.tar.gz linux-pkg

          # Stage 3: Create minimal runtime image
          FROM scratch as export
          COPY --from=builder /app/dist /

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ramble-linux-amd64
        path: ./dist/ramble-linux-amd64.tar.gz
        if-no-files-found: error

  release:
    needs: build-linux
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: ramble-linux-amd64
        path: ./dist

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/ramble-linux-amd64.tar.gz