name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libasound2-dev libgtk-3-dev

    - name: Set up vendor directory
      run: |
        # Create vendor directories
        mkdir -p vendor/whisper/include
        mkdir -p vendor/whisper/lib

        # Download pre-built whisper library for CI
        curl -L -o whisper.h https://raw.githubusercontent.com/ggerganov/whisper.cpp/master/whisper.h
        cp whisper.h vendor/whisper/include/

        # Copy libraries from artifact server (replace with your actual artifact URL)
        # curl -L -o vendor/whisper/lib/libwhisper.so https://your-artifact-server.example/libwhisper.so
        # For CI, use a simple stub library
        echo "// Stub library for CI" > stub.c
        gcc -shared -o vendor/whisper/lib/libwhisper.so stub.c
        ln -s libwhisper.so vendor/whisper/lib/libwhisper.so.1

    - name: Build
      run: |
        export LD_LIBRARY_PATH=$(pwd)/vendor/whisper/lib:$LD_LIBRARY_PATH
        export CGO_CFLAGS="-I$(pwd)/vendor/whisper/include"
        export CGO_LDFLAGS="-L$(pwd)/vendor/whisper/lib -lwhisper"
        go build -v ./...